name: clang-format

on:
  workflow_call:

jobs:
  formatting-check:
    name: Verify Formatting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path:
          - src
          - tests

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format-20

      - name: Verify formatting (${{ matrix.path }})
        run: |
          find ${{ matrix.path }} \( -name '*.cpp' -o -name '*.hpp' \) -print0 | \
          xargs -0 clang-format-20 --dry-run --Werror
